version: '3.8'
services:
  mqtt:
    image: eclipse-mosquitto
    container_name: mqtt-broker
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mqtt/config:/mosquitto/config
      - ./mqtt/data:/mosquitto/data
      - ./mqtt/log:/mosquitto/log
    networks:
      - app-network


  cassandra-seed:
    image: cassandra:latest
    container_name: cassandra
    ports:
      - "9042:9042"
    environment:
      - CASSANDRA_CLUSTER_NAME=SecurityCluster
      - CASSANDRA_NUM_TOKENS=256
      - MAX_HEAP_SIZE=512M
      - HEAP_NEWSIZE=128M
    volumes:
      - ./cassandra:/var/lib/cassandra
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "cqlsh -e 'describe keyspaces'"]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 0s

  cassandra-node1:
    image: cassandra:latest
    container_name: cassandra-node1
    environment:
      - CASSANDRA_CLUSTER_NAME=SecurityCluster
      - CASSANDRA_NUM_TOKENS=256
      - CASSANDRA_SEEDS=cassandra-seed
      - MAX_HEAP_SIZE=512M
      - HEAP_NEWSIZE=128M
    volumes:
      - ./cassandra-node1:/var/lib/cassandra
    networks:
      - app-network
    depends_on:
      cassandra-seed:
        condition: service_healthy

  cassandra-node2:
    image: cassandra:latest
    container_name: cassandra-node2
    environment:
      - CASSANDRA_CLUSTER_NAME=SecurityCluster
      - CASSANDRA_NUM_TOKENS=256
      - CASSANDRA_SEEDS=cassandra-seed
      - MAX_HEAP_SIZE=512M
      - HEAP_NEWSIZE=128M
    volumes:
      - ./cassandra-node2:/var/lib/cassandra
    networks:
      - app-network
    depends_on:
      cassandra-seed:
        condition: service_healthy

  controller:
    image: pedroaniciodev/security-system-backend
    build:
      context: .
      dockerfile: security-system-backend/Dockerfile
    ports:
      - "8080-8081:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - MQTT_BROKER_URL=tcp://mqtt:1883
      - CASSANDRA_HOST=cassandra
      - MAX_HEAP_SIZE=512M
      - HEAP_NEWSIZE=128M
    depends_on:
      mqtt:
        condition: service_started
      cassandra-seed:
        condition: service_healthy
      cassandra-node1:
        condition: service_started
      cassandra-node2:
        condition: service_started
    deploy:
      replicas: 2 # instancias do controller
      restart_policy:
        condition: on-failure
    networks:
      - app-network

networks:
  app-network:
    driver: bridge