version: '3.8'
services:
  mqtt:
    image: eclipse-mosquitto
    container_name: mqtt-broker
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mqtt/config:/mosquitto/config
      - ./mqtt/data:/mosquitto/data
      - ./mqtt/log:/mosquitto/log
    networks:
      - app-network


  cassandra:
    image: cassandra:latest
    container_name: cassandra
    ports:
      - "9042:9042"
    environment:
      - CASSANDRA_CLUSTER_NAME=SecurityCluster
      - CASSANDRA_NUM_TOKENS=256
    volumes:
      - ./cassandra:/var/lib/cassandra
    networks:
      - app-network

  controller:
    image: pedroaniciodev/security-system-backend
    build:
      context: .
      dockerfile: security-system-backend/Dockerfile
    ports:
      - "8080-8081:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - MQTT_BROKER_URL=tcp://mqtt:1883
      - CASSANDRA_HOST=cassandra
    depends_on:
      - mqtt
      - cassandra
    deploy:
      replicas: 1 # instancias do controller
      restart_policy:
        condition: on-failure
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - controller
    networks:
      - app-network


networks:
  app-network:
    driver: bridge
