version: '3.8'

services:
  app1:
    build: ./
    ports:
      - "5000:5000"
    networks:
      - blockchain_net
  
  app2:
    build: ./
    ports:
      - "5001:5000"
    networks:
      - blockchain_net
  
  app3:
    build: ./
    ports:
      - "5002:5000"
    networks:
      - blockchain_net

networks:
  blockchain_net:
    driver: bridge
